openapi: 3.0.3
info:
  title: API
  version: "1.0"
  description: |-
    Issue, hold, transfer and redeem tokens. Backed by a distributed ledger,
    preserving privacy using Zero Knowledge Proofs. This API definition fronts 4 different services, which each play a different
    role in the ecosystem. 

    To try it out, let the Issuer issue some funds to one of the users. Watch the balances
    get updated and see the transaction history. Transfer it to another account, or redeem
    the tokens to destroy them.
servers:
  - url: http://localhost:3000/api/
    description: server

tags:
  - name: land dept
    description: Land department
  - name: 3rd party
    description: 3rd party
  - name: operations
    description: Health check operations

paths:
  /assets:
    get:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"

      summary: Get an account and their balance of a certain type

  /land/assets/list:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"

      summary: Get an account and their balance of a certain type

  /land/assets/find:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/propertyReferenceNumber"
        - $ref: "#/components/parameters/address"
        - $ref: "#/components/parameters/limit"
          required: true
        - $ref: "#/components/parameters/offset"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an account and their balance of a certain type

  /land/assets/get/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an account and their balance of a certain type
  /land/assets/history/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an account and their balance of a certain type
  /land/assets/create:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/import:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/update/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/delete/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /land/assets/lock/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /land/assets/unlock/{id}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/transaction/approve/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/transaction/reject/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/incumbrance/approve/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
  /land/assets/incumbrance/reject/{id}/{recordIndex}:
    post:
      tags:
        - land dept
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
      summary: Get all transactions for an account
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"

  /3rdParty/assets/find:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      parameters:
        - $ref: "#/components/parameters/id"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/ListSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get an account and their balance of a certain type

  /3rdParty/assets/get/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/GetAssetWithDetailSuccess"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get all accounts on this node and their balances of each type
  /3rdParty/assets/transaction/submit/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get all accounts on this node and their balances of each type
  /3rdParty/assets/incumbrance/submit/{id}:
    post:
      tags:
        - 3rd party
      security:
        - X-Api-Key: []
      responses:
        "200":
          $ref: "#/components/responses/SuccessResponse"
        default:
          $ref: "#/components/responses/ErrorResponse"
      summary: Get all accounts on this node and their balances of each type

  # Operations
  /healthz:
    get:
      tags:
        - operations
      summary: Returns 200 if the service is healthy
      responses:
        "200":
          $ref: "#/components/responses/HealthSuccess"
        "503":
          $ref: "#/components/responses/ErrorResponse"
  /readyz:
    get:
      tags:
        - operations
      summary: Returns 200 if the service is ready to accept calls
      responses:
        "200":
          $ref: "#/components/responses/HealthSuccess"
        "503":
          $ref: "#/components/responses/ErrorResponse"

components:
  responses:
    ListSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
              - payload
            properties:
              count:
                type: integer
                example: 1
              message:
                type: string
                example: "ok"
              rows:
                type: array
                items:
                  $ref: "#/components/schemas/SimpleAsset"

    GetAssetWithDetailSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
              - payload
            properties:
              message:
                type: string
              payload:
                $ref: "#/components/schemas/Asset"

    HealthSuccess:
      description: Success response
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: ok
            example:
              message: ok
    SuccessResponse:
      description: Success response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Success"
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    SimpleAsset:
      type: object
      description: Information about an account and its balance
      required:
        - id
        - propertyReferenceNumber
      properties:
        id:
          type: string
          description: account id as registered at the Certificate Authority
          example: alice
        propertyReferenceNumber:
          type: string
          description: the property reference number
        propertyHeldInfos:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/PropertyHeldInfo"
        propertyAddress:
          type: string
          description: the property address
        propertyChineseAddress:
          type: string
          description: the property chinese address
      example:
        id: 1
        propertyReferenceNumber: "PRN-001"
        propertyHeldInfos:
          - locationNumber: "Lot 1"
            heldUnder: "PRN-001"
            leaseTerm: "1 year"
            commencementOfLeaseTerm: "2021-01-01"
            rentPerAnnum: ""
        propertyAddress: "english address"
        propertyChineseAddress: "chinese address"
    Asset:
      type: object
      description: Information about an account and its balance
      required:
        - id
        - propertyReferenceNumber
      properties:
        id:
          type: string
          description: account id as registered at the Certificate Authority
          example: alice
        version:
          type: string
          description: the property reference number
        createdAt:
          type: string
          description: balance in base units for each currency
        updatedAt:
          type: string
          description: the property address
        createdMethod:
          type: string
          description: the property chinese address
        propertyStatus:
          type: string
          description: the property chinese address

        propertyReferenceNumber:
          type: string
          description: the property reference number
        propertyHeldInfos:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/PropertyHeldInfo"
        propertyAddress:
          type: string
          description: the property address
        propertyChineseAddress:
          type: string
          description: the property chinese address
        propertyShareOfTheLocation:
          type: string
          description: the property chinese address
        propertyRemarks:
          type: array
          description: balance in base units for each currency
          items:
            type: string
        transactionHistory:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        deedsPendingRegistration:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        deedsPendingRegistrationRejected:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/OwnerTransactionInfo"
        incumbranceHistory:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
        incumbrancePendingRegistration:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
        incumbrancePendingRegistrationRejected:
          type: array
          description: balance in base units for each currency
          items:
            $ref: "#/components/schemas/IncumbrancesInfo"
    PropertyHeldInfo:
      type: object
      description: Information about an account and its balance
      required:
        - locationNumber
        - heldUnder
        - leaseTerm
        - commencementOfLeaseTerm
        - rentPerAnnum
      properties:
        locationNumber:
          type: string
          description: account id as registered at the Certificate Authority
          example: alice
        heldUnder:
          type: string
          description: the property reference number
        leaseTerm:
          type: string
          description: balance in base units for each currency
        commencementOfLeaseTerm:
          type: string
          description: the property address
        rentPerAnnum:
          type: string
          description: the property chinese address
      example:
        locationNumber: 1
        heldUnder: "PRN-001"
        leaseTerm: "1 year"
        commencementOfLeaseTerm: "2021-01-01"
        rentPerAnnum: ""
    OwnerInfo:
      type: object
      description: Information about an account and its balance
      required:
        - nameOfOwner
        - capacity
      properties:
        nameOfOwner:
          type: string
          description: account id as registered at the Certificate Authority
          example: alice
        capacity:
          type: string
          description: the property reference number
      example:
        nameOfOwner: "alice"
        capacity: "all"
    OwnerTransactionInfo:
      type: object
      description: Information about an account and its balance
      required:
        - owners
        - memorialNumber
        - dateOfInstrument
        - dateOfRegistration
        - consideration
        - remarks
      properties:
        owners:
          type: array
          description: account id as registered at the Certificate Authority
          items:
            $ref: "#/components/schemas/OwnerInfo"
        memorialNumber:
          type: string
          description: account id as registered at the Certificate Authority
          example: memorialNumber
        dateOfInstrument:
          type: string
          description: the property reference number
          example: dateOfInstrument
        dateOfRegistration:
          type: string
          description: balance in base units for each currency
          example: dateOfRegistration
        consideration:
          type: string
          description: the property address
          example: consideration
        remarks:
          type: string
          description: the property chinese address
          example: remarks field

    IncumbrancesInfo:
      type: object
      description: Information about an account and its balance
      required:
        - memorialNumber
        - dateOfInstrument
        - dateOfRegistration
        - natureOfIncumbrances
        - inFavourOf
        - consideration
        - remarks
      properties:
        owners:
          type: array
          description: account id as registered at the Certificate Authority
          items:
            $ref: "#/components/schemas/OwnerInfo"
        memorialNumber:
          type: string
          description: account id as registered at the Certificate Authority
          example: memorialNumber
        dateOfInstrument:
          type: string
          description: the property reference number
          example: dateOfInstrument
        dateOfRegistration:
          type: string
          description: balance in base units for each currency
          example: dateOfRegistration
        natureOfIncumbrances:
          type: string
          description: the property address
          example: natureOfIncumbrances
        inFavourOf:
          type: string
          description: the property address
          example: inFavourOf
        consideration:
          type: string
          description: the property address
          example: consideration
        remarks:
          type: string
          description: the property chinese address
          example: remarks field

    Success:
      required:
        - message
        - payload
        - id
      type: object
      properties:
        message:
          description: High level success message
          type: string
        payload:
          description: Details about the data (object/json/string)
          type: string
        id:
          description: Details about the id
          type: string
      example:
        message: success message
        payload: "{}"
        id: "asset_id"
    Error:
      required:
        - message
        - payload
      type: object
      properties:
        message:
          description: High level error message
          type: string
        payload:
          description: Details about the error
          type: string
      example:
        message: error message
        payload: ""
  parameters:
    id:
      name: id
      schema:
        example: asset id
        description: asset id
        type: string
      in: path
      required: true
    limit:
      name: limit
      in: query
      schema:
        example: 10
        description: limit
        type: number
      required: true
    offset:
      name: offset
      in: query
      required: true
      schema:
        example: 0
        description: offset
        type: number
    propertyReferenceNumber:
      name: propertyReferenceNumber
      in: query
      schema:
        example: "PRN-001"
        description: The Property Reference Number
        type: string
    address:
      name: address
      in: query
      schema:
        example: "address"
        description: The address of the property
        type: string
  securitySchemes:
    X-Api-Key:
      type: apiKey
      in: header
      name: X-Api-Key
  headers: {}

security: []
